export const ALL_STYLE_PROPERTIES = [
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'width',
  'height',
  'max-width',
  'max-height',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'font-family',
  'font-size',
  'font-weight',
  'color',
  'letter-spacing',
  'line-height',
  'text-align',
  'text-decoration',
  'background-color',
  'border-width',
  'border-color',
  'border-style',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'box-shadow',
  'opacity',
  'z-index',
  'flex-direction',
  'align-items',
  'justify-content'
];

export const DEFAULT_PROPERTY_VALUES: Record<string, string> = {
  'display': 'block',
  'position': 'static',
  'top': '0px',
  'right': '0px',
  'bottom': '0px',
  'left': '0px',
  'width': 'auto',
  'height': 'auto',
  'max-width': 'none',
  'max-height': 'none',
  'margin-top': '0px',
  'margin-right': '0px',
  'margin-bottom': '0px',
  'margin-left': '0px',
  'padding-top': '0px',
  'padding-right': '0px',
  'padding-bottom': '0px',
  'padding-left': '0px',
  'font-family': 'inherit',
  'font-size': '16px',
  'font-weight': '400',
  'color': '#000000',
  'letter-spacing': '0px',
  'line-height': '1.5',
  'text-align': 'left',
  'text-decoration': 'none',
  'background-color': 'transparent',
  'border-width': '0px',
  'border-color': '#000000',
  'border-style': 'solid',
  'border-top-left-radius': '0px',
  'border-top-right-radius': '0px',
  'border-bottom-left-radius': '0px',
  'border-bottom-right-radius': '0px',
  'box-shadow': 'none',
  'opacity': '1',
  'z-index': '0',
  'flex-direction': 'row',
  'align-items': 'stretch',
  'justify-content': 'flex-start'
};